default: &default
   adapter: postgresql
   encoding: unicode

development:
   adapter: postgresql
   encoding: unicode
   database: ehr_development
   username: <%= ENV['POSTGRES_USERNAME'] %>
   password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
   adapter: postgresql
   encoding: unicode
   database: ehr_test
   username: <%= ENV['POSTGRES_USERNAME'] %>
   password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
   adapter: postgresql
   encoding: unicode
   database: <%= ENV['YOUR_DATABASE_NAME'] %>
   username: <%= ENV['YOUR_DATABASE_USERNAME'] %>
   password: <%= ENV['YOUR_DATABASE_PASSWORD'] %>
